### ISSUE TITLE
Assignment

### ISSUE THREAD

**Issue by obroma** [NESREA/GitPractice#1]
i have been able to clone GitPractice as instructed but into a new folder opened, but the problem i'm having now is to save or copy the text into notepad

**Comment by BroVic** [comment]
What I meant is that use the text editor called Notepad to open the file and edit the file **lorem-ipsum.txt**. This works mostly for Windows users and the shell command is simple

`notepad lorep-ipsum.txt`
You do not need to copy and paste anything - just use the program to open the file so that you can view and edit its contents. When you're done, just close the file by closing the window.

For Mac OS X, one would probably use `emacs` instead.

_**Addendum**_:
If you want to be adventurous, use `vi` or `vim` command in bash to the file in other shell-based text editors. To edit here you type `CTRL + A` and in the status bar below you will see it written INSERT (meaning you can now edit). When you're through, save and exit the application with these keyboard shortcuts: ` ESC` -> ` :`  -> `w` -> `q`.

**Comment by BroVic** [comment]
If there is no further question, I'm closing this issue.
